nodeLinker: node-modules
enableGlobalCache: true
compressionLevel: 0
enableInlineBuilds: true
cacheFolder: ./.yarn/cache
nmMode: hardlinks-local

# Reduce disk usage during builds
enableTelemetry: false
enableProgressBars: false

# Production settings
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0062
    level: discard

# Optimizations
pnpEnableInlining: true
