# wrangler.toml - Cloudflare Pages 配置文件
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


name = "github-card"
compatibility_date = "2023-05-18"
main = ".cloudflare/workers-site/index.js"
compatibility_flags = ["nodejs_compat"]

# 静态资源路由配置
[site]
bucket = ".output"

# Pages构建输出目录配置
pages_build_output_dir = ".next"

# KV 命名空间配置

[[kv_namespaces]]
binding = "GITHUB_CARD_KV"
id = "ee963ddf7c4d40c5bf12bb090b0c46fb"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "github-card-db"
database_id = "86b1aef5-6719-4c86-b43d-300bda4da793"
migrations_dir = "drizzle/migrations"
# 注意: 需要在 Cloudflare Dashboard 中找到已创建的 D1 数据库的 ID
# 并替换上面的占位符为真实的 database_id

# 环境变量配置
[vars]
# 运行时需要的环境变量可以在Cloudflare Pages后台界面配置

[env.production]
name = "github-card-production"
route = "*"

[env.development]
# 开发环境特定配置
workers_dev = true

# Next.js 特定构建命令
[build]
command = "yarn build"
output_directory = ".output"
watch_dir = "src" # 监视此目录中的更改