# wrangler.toml - Cloudflare Pages 配置文件
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


name = "github-card"
compatibility_date = "2023-05-18"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat"]

# 静态资源路由配置
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# KV 命名空间配置

[[kv_namespaces]]
binding = "GITHUB_CARD_KV"
id = "ee963ddf7c4d40c5bf12bb090b0c46fb"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "github-card-db"
database_id = "86b1aef5-6719-4c86-b43d-300bda4da793"
migrations_dir = "drizzle/migrations"
